name: Release Container Image

on:
  push:
    branches:
      - main
    paths:
      - "VERSION"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: doda2025-team22/model-service
  BUILD_ID: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Read current VERSION
        id: version
        run: |
          VERSION=$(cat VERSION)
          MAJOR=$(echo "$VERSION" | cut -d . -f 1)
          MINOR=$(echo "$VERSION" | cut -d . -f 2)
          PATCH=$(echo "$VERSION" | cut -d . -f 3)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "VERSION_MINOR=$MINOR" >> $GITHUB_ENV
          echo "VERSION_PATCH=$PATCH" >> $GITHUB_ENV

      - name: Log version
        run: |
          echo "Building version ${{ env.VERSION }}"
          echo "Major: ${{ env.VERSION_MAJOR }}, Minor: ${{ env.VERSION_MINOR }}, Patch: ${{ env.VERSION_PATCH }}"

      - name: Log in ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch image image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            BACKEND_PORT=8081
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}.${{env.BUILD_ID}}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_MAJOR }}.${{env.BUILD_ID}}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.BUILD_ID}}
